### ISSUE TITLE
Missing SQL tables

### ISSUE THREAD

**Issue by PrimeAltis** [ins0/armasquads#110]
After importing database.sql

[STDERR] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'squadxml.auth_role' doesn't exist'

Also auth_role_roles & auth_user_role missing and no defined user roles

Is there an updated import available?

Thanks

**Comment by ins0** [comment]
yes i will update the db dump in a few minutes - thanks!
