### ISSUE TITLE
ArmA 3 Squad XML not working

### ISSUE THREAD

**Issue by Hvitsen** [ins0/armasquads#114]
So I've created a whole squad, everything is saved. But for I and the rest of the squad, the arma squads url doesn't show the picture or information.
http://armasquads.com/user/squads/xml/aknAHP5leqk3idFFLaaNu7vXIwRf21uw/squad.xml'

The image size is 256x256

Image of Squad.dtd: https://gyazo.com/3b033b8e57416efcbaae58ecdb85953e

**Comment by MLGLYNN** [comment]
Also having this issue.
