### ISSUE TITLE
Cannot change password

### ISSUE THREAD

**Issue by Sterbinator** [ins0/armasquads#115]
Hey!

Everytime i try to change my password it says: An exception has been raised within the callback

**Comment by ins0** [comment]
Hey @Sterbinator will will have a look today!

**Comment by XylofonKobra414** [comment]
I've forgotten my Password and I send an Email.... I got no reply so far... even though that was your suggestion in another thread here I could send another one if you want ?! Or you build in a "Forgot your Password?" function

**Comment by Marco112** [comment]
where can I reset my password ?

**Comment by healthstr** [comment]
There is currently no way to reset your password you will need an admin to do it.

**Comment by ins0** [comment]
@Marco112 please send me an email form your registered email to "rieger@racecore.de"

**Comment by ins0** [comment]
fixed with pull #140
