### ISSUE TITLE
ArmA 3 Squad XML not working

### ISSUE THREAD

**Issue by kongkaeng** [ins0/armasquads#117]
So I've created a whole squad, everything is saved. But for I and the rest of the squad, the arma squads url doesn't show the picture or information.
http://armasquads.com/user/squads/xml/lxFT7x2osK1ccACfiYiKfDfHDJDSH6fJ/squad.xml

**Comment by darkethan** [comment]
I have the same problem i created the SquadXML and its not working


http://armasquads.de/user/squads/xml/6WppbF53UVt7qZUtltqWi1DQ5Z5WWrfx/squad.xml

**Comment by ins0** [comment]
Hey @kongkaeng @darkethan . I don't own a Arma Server to lookup the server logs and investigate if this is a general problem with the xml files or specific with the details in your xmls. May you can provide  some server logs?
