### ISSUE TITLE
SquadXML not working

### ISSUE THREAD

**Issue by darkethan** [ins0/armasquads#118]
Ich habe eine SquadXML erstellen wollen aber wenn ich den Link bei Arma ins Profil einfüge passiert einfach nichts.

I created a SquadXML but the problem is when i launch Arma and join on a server the XML is not working

http://armasquads.de/user/squads/xml/6WppbF53UVt7qZUtltqWi1DQ5Z5WWrfx/squad.xml

**Comment by ins0** [comment]
Bitte entferne die ``_`` aus der XML und versuche es erneut, ich kann leider nichts zum Fehler sagen da Arma nur sehr geringfügig das Debuggen der XMLs erlaubt.

**Comment by darkethan** [comment]
Das _gehört aber zu meinem Namen 
:O
