### ISSUE TITLE
Squad image is not working

### ISSUE THREAD

**Issue by DivinityRSPS** [ins0/armasquads#121]
http://armasquads.de/user/squads/xml/OSSTBqzwvvdXKJirOTmh0jt3GTvKZsYx/squad.xml

My image is not showing up in game, any ideas why? i also tried to resize it, it wont work.

**Comment by healthstr** [comment]
hello could you show me an image from in game as I can not see an issue here.

**Comment by DivinityRSPS** [comment]
https://gyazo.com/16b802e3c263ef759fa68d3d60c462f8

**Comment by healthstr** [comment]
Hello 
Im not sure as your image is there and I have also downloaded the image and it works fine, let me know if this still an issue.

**Comment by ins0** [comment]
I updated the paa conversation, maybe this help - try if this works better now. Feel free to open this issue again.
