### ISSUE TITLE
Squad.xml doesn't show up in-game (no information)

### ISSUE THREAD

**Issue by citrinase** [ins0/armasquads#123]
Hello, 
This is my squad.xml http://armasquads.com/user/squads/xml/4Oi3WKWSIDZFSkEZ1CVrpt4m4VIY2UXZ/squad.xml
I tried to find the problem on the internet but didnt managed to fix it, i am sure that i dind't missed any step because i was wathcing youtube videos and it seems its simple but still nothing works.
Btw, url addres is in the game, didn't forgot that.
Ty for help, citrinase.

**Comment by citrinase** [comment]
Oh and server let's you have the squads url's

**Comment by citrinase** [comment]
I found it out by myself, ty anyway.

**Comment by ins0** [comment]
@citrinase 
Thanks for your reply. Could you please also tell what was the error and the solution?
