### ISSUE TITLE
How to Delete Account/Change it's name

### ISSUE THREAD

**Issue by PK-IllinoisFIN** [ins0/armasquads#124]
I would like to change or delete my account so i could create new one with different name.

Reason: I have multiple friends who are playing arma3 and i would like to have account that our admins could use to update players .xml stats.

I have tried to create a new account but it won't allow to have accounts with same Email.

Is there way to change accounts username?

**Comment by healthstr** [comment]
Hello
Currently there is no way to delete or change username on your account, the only way to do this is for a admin to edit the database to change your username. In updates username change or account deletion maybe possible.

**Comment by PK-IllinoisFIN** [comment]
Requesting account username change. New: 7CavACV

**Comment by healthstr** [comment]
Whats your current username?

**Comment by PK-IllinoisFIN** [comment]
Profile Details
Illi.H Username
pk-illinois@hotmail.com E-Mail
Mar 31, 2016, 4:49:33 PM Register Date
Apr 2, 2016, 2:34:37 PM Last Login

**Comment by healthstr** [comment]
At the moment it does not work, work seems to have stop on the project at the moment but I am looking to start working on it.

**Comment by ins0** [comment]
@PK-IllinoisFIN 
ill change your name.

@healthstr 
thanks!

**Comment by PK-IllinoisFIN** [comment]
Thanks m8!
