### ISSUE TITLE
No Clan Tag in-game or Squad Logo

### ISSUE THREAD

**Issue by NessMonster** [ins0/armasquads#125]
Hello Armasquad.  I Just created a new arma Squad because the old one didnt work.

but when i go in-game there is no Clan tag or Clan Logo.  
when i click on my name there is only the Clan name and tittle uknow. 

http://armasquads.com/user/squads/xml/2nypD00jlhfcxoGBRbGr4kjATlpiX8c8/squad.xml

**Comment by healthstr** [comment]
from the looks of the XML view everything seems to be fine could you send an email of in game or if there is a debug message.

**Comment by ins0** [comment]
Thank you so much for responding to this tickets luke, much appreciate. Dont have much time. 

> there is a debug message

thats the problem with squad xmls - the only debug is server side and not much detailed. Friend of mine tried the xml on his server and everything works fine. So the problem must be serverside or some special type of characters used etc. idk either.

**Comment by healthstr** [comment]
Yea I have an XML on armasquads and everything seems to working fine.
