### ISSUE TITLE
Logo not working

### ISSUE THREAD

**Issue by LeerianDark** [ins0/armasquads#129]
I know try it like 20 min...
I convert it from png to jpg and again to png and nothing is working...
The Tag is working but when i look under players i just see a empty picture but there is a blank
http://armasquads.de/user/squads/xml/Yf2UlNLdUaiIIA3j2XKLypet5VItONjk/squad.xml
pls help me... this isnt my first one and the other ones are all working

Mfg. Leerian Dark from Germany

**Comment by healthstr** [comment]
Hello @LeerianDark Sorry it seem your having this issue could share the image with me so I can try replicate the issue my side for debugging.

**Comment by LeerianDark** [comment]
http://img5.fotos-hochladen.net/uploads/logohd0r264cno.png

 this is the picture try your best.. and thx ^^

**Comment by healthstr** [comment]
hello could you remove any special characters from your xml such as / * - ! "# $%&/(().-:;_

**Comment by LeerianDark** [comment]
thx it worked i delet them all ^^ 

for all now if you got special characters in your squad xml it workes

**Comment by ins0** [comment]
thanks @healthstr for support and @LeerianDark for your feedback :+1:
