### ISSUE TITLE
No Logo on a vehicle

### ISSUE THREAD

**Issue by TheLeonDemon** [ins0/armasquads#130]
hey ^^
i see my logo ingame under my name and the squad but no logo in my vehicle...

**Comment by antoniopaladin** [comment]
i cant see my logo in game or anywhere idk how to fix that aswell

**Comment by antoniopaladin** [comment]
i managed to fix picture dont use any of this in squad tag  / * - ! "# $%&/(().-:;_ or you wont see any logo or picture  
maybe it helps

**Comment by TheLeonDemon** [comment]
@antoniopaladin i dont have one of this in my logo ^^ but thanks

**Comment by healthstr** [comment]
hello could you link your squad xml please

**Comment by TheLeonDemon** [comment]
@healthstr http://armasquads.com/user/squads/xml/9vgbhbS6WJJv3TBC8jAbDrIXI7Gd1EoR/squad.xml

**Comment by ins0** [comment]
don't see any special characters in your xml, maybe the server won't allow squad xmls? This are squad xmls where i don't know why this sort of stuff won't work by arma clients.

**Comment by healthstr** [comment]
The only thing I can suggest is create a local server on your computer and test it that way.

**Comment by ins0** [comment]
I updated the paa conversation, maybe this help - try if this works better now. Feel free to open this issue again.
