### ISSUE TITLE
Logo/Invisible not working

### ISSUE THREAD

**Issue by antoniopaladin** [ins0/armasquads#131]
Logo is invisible when i try to look at it in arma 3 idk how to fix  can someone help fix the picture or help me  and if someone can fix it and reupload it thanks for any reply 
here is the imgur link 
http://imgur.com/PaWygFS

squad Xml 
http://armasquads.com/user/squads/xml/aCeJrEBCGyu098S7rhjx0IUuAF0DWQ5b/squad.xml
-----------------------------------------------------------------------------------------------------------------------
i tryed changing the image size 
to 256x256 like it says  it uploads fine to squad picture but its not showing up
Thanks if anyone helps 

 MANAGED TO GET IT FIXED         IF U HAVE   * IN SQUAD TAG  LOGO DOSENT WORK

**Comment by antoniopaladin** [comment]
MANAGED TO GET IT FIXED         IF U HAVE   * IN SQUAD TAG  LOGO DOSENT WORK

**Comment by healthstr** [comment]
ok thank you for the feedback :)

**Comment by ins0** [comment]
Thanks @antoniopaladin and @healthstr for providing help and feedback :+1:
