### ISSUE TITLE
No Details or Logo

### ISSUE THREAD

**Issue by Windy5000** [ins0/armasquads#132]
Hello, 

I mainly play on KOTH Hostiletakeover.co servers, followed all instructions for making a squad with no success. 

Copy & pasted this into my Arma 3 player profile:  
http://armasquads.com/user/squads/xml/7Ow9kp4gqETlj20YTEGeMLujGGikc59T/squad.xml

Do I by chance have to have the files placed locally on my computer? Other players seem to have theirs working fine. Any help is much appreciated!

- Windy

**Comment by healthstr** [comment]
Hey, it seems that you have not connected a arma profile to your xml.

**Comment by Windy5000** [comment]
Ah ok, 

Will update and confirm it works, sorry I didn't know you had to do that. 

:)

**Comment by Windy5000** [comment]
Apologies, everything seems to be working fine.

**Comment by ins0** [comment]
Thanks @healthstr @Windy5000
