### ISSUE TITLE
No Squadinfo, no Squadpicture

### ISSUE THREAD

**Issue by PeterJaeger** [ins0/armasquads#134]
Hello guys,
I created a squad on your website, but it's not working... 

Squad.xml:
http://armasquads.com/user/squads/xml/Oh2QlCyaYFZinnD7TqViEiFyU09fyNcY/squad.xml

Ingame pic:
http://www.fotos-hochladen.net/uploads/arma3error4jltpsy0gu.jpg

It only shows playerinfo I edited in the Squad.xml but there is no squadinfo showing up

Please help me fast!

**Comment by healthstr** [comment]
Could you try re-uploading the image it seems that its not on the website.
