### ISSUE TITLE
ArmA Squad, only remark is showing for some squad members

### ISSUE THREAD

**Issue by alundy1262** [ins0/armasquads#136]
Hello, I have a squad I run with in Arma 3. When in game three members(SuicideKats, Jax, and Keotis) show only the remake and nothing else. When I change their remark it will change in game so I know there profile is connected to armasquad.xml. Here is the the xml file:  http://armasquads.com/user/squads/xml/pR09LUXWstMfLsqbUdjfzdj3mRR0UUk5/squad.xml

**Comment by alundy1262** [comment]
http://images.akamai.steamusercontent.com/ugc/271718911516509697/DC72CF53CC334484D486227DE5285F1E9935C233/  This is a picture of SuicideKats profile in game

**Comment by healthstr** [comment]
Hello under the user SuicideKats there is no data in there name or anything else just there remark which is why you getting this issue.

<member id="76561198031148718" nick="Suicidekats">
<name>N/A</name>
<email>N/A</email>
<icq>N/A</icq>
<remark>When the claws come out</remark>
</member>

**Comment by alundy1262** [comment]
OK, so I filled in all of the squads info. The real issue I am having I can get the squad info to show. Here is the my profile in game: http://images.akamai.steamusercontent.com/ugc/264964143179997878/C44706D7892A0C24C346D38F85C1A88640DB01BC/
here is Suicidekats current in game profile: http://images.akamai.steamusercontent.com/ugc/264964143181727279/8BE2347BBC8BE227367B1700CF37050BFD93198F/

notice the squad picture, the tag in the player list, or the squad information doesn't show

**Comment by alundy1262** [comment]
here is jax: http://images.akamai.steamusercontent.com/ugc/264964143181753243/31E26F353EBA3F5F0D532C4708C839E83515C0F5/

**Comment by healthstr** [comment]
Hello, sorry but I don't think this an armasquads issue as it does work with some of your members the only to test this is to host the xml on something like web space or something and test it that way.

**Comment by ins0** [comment]
Closing this. Feel free to open this issue again.
