### ISSUE TITLE
Logo not showing

### ISSUE THREAD

**Issue by LtWulff** [ins0/armasquads#137]
Created my squad and the logo should be just fine but it isn't showing on neither vehicle, uniform or playerlist.
Squad url shown below:
http://armasquads.com/user/squads/xml/H4C9QzqxGz5HrraZgFIRX4Iu0b23OltY/squad.xml

**Comment by ins0** [comment]
I updated the paa conversation, maybe this help - try if this works better now. Feel free to open this issue again.
