### ISSUE TITLE
SQUAD Logo Not displaying due to website URL

### ISSUE THREAD

**Issue by TheToRN** [ins0/armasquads#139]
First thanks to devs for the site, much appreciated.

I had an issue where by the squad system was not working, this was due to the URL for the website specified on the Squad info. 

Our Arma server was showing errors 

17:34:40 Warning: Could not parse squad.xml for Player[TheToRN], Squad[http://armasquads.com/user/squads/xml/................./squad.xml]

Once i removed the URL for the website the Squad system works perfect now.

**Comment by ins0** [comment]
Hey @TheToRN thank you very much for this information. Currently i can't indicate why this error is generated, if i get another confirmation about this one i will take action and remove the url temporary.
