### ISSUE TITLE
Squad XML not working at all

### ISSUE THREAD

**Issue by Wuler** [ins0/armasquads#143]
I can't get this to work, not showing up at all, tried doing it for all profiles, tried changing things, tried making a completely new squad and it won't work whatsoever.

http://armasquads.com/user/squads/xml/iIuEg6Nhm6ey88csvm6hwvgIaOx80b5C/squad.xml

**Comment by BetterDeadThanZed** [comment]
https://github.com/ins0/armasquads/issues/145
