### ISSUE TITLE
xml not working with apex update 1.64

### ISSUE THREAD

**Issue by icebox84** [ins0/armasquads#145]
My patch shows up on my shoulder. and my tag shows up next to my name. But no info is on my player Info, on the players section in the map. Worked before the update for apex yesterday of 5 gigs. Now after the update, xml on armasquads.com not working correctly. I updated my player id and put new xml link to profile, restarted, defraged or tried to defrag my ssd. Still same problem exist.

**Comment by BetterDeadThanZed** [comment]
This is also happening to me. Any advice? Is it broken?

**Comment by ins0** [comment]
Will have to look at this issue tonight when i'm back home. Thanks for the report guys.

**Comment by icebox84** [comment]
thanks buddy, i will donate too you this friday if the problem is resolved. 

    On Tuesday, October 11, 2016 2:25 AM, Marco Rieger <notifications@github.com> wrote:
 

 Will have to look at this issue tonight when i'm back home. Thanks for the report guys.—

**Comment by BetterDeadThanZed** [comment]
Did you have a chance to look into this? Only the tag/logo is working. Nothing else.
