### ISSUE TITLE
Password recovery to ArmAsquads.com

### ISSUE THREAD

**Issue by Roumenn** [ins0/armasquads#146]
Hi, I forgot my password to my arma 3 squad and there is no recovery option. Could you help me with that pls?

**Comment by healthstr** [comment]
Hello, please send @ins0 an email from your registered account email to ins0@racecore.de he will send you afterwards the temporary account password

**Comment by ins0** [comment]
There is currently no reset login feature implemented. Feel free to help and/or develop this feature.
