### ISSUE TITLE
Squad logo is not showing up

### ISSUE THREAD

**Issue by kim666166** [ins0/armasquads#158]
when i open zeus in game, it has an error message like 'Cannot load texture c:\users\mycomputer\appdata\local\arma 3\squads\udt/seal\15f0e9a2c01b8c37701f1c2181be11a5.paa.'.

i already tried 16x16, 32x32, 64x64, 128x128 and 256x256.. .but it still dont work...

**Comment by kim666166** [comment]
http://armasquads.com/user/squads/xml/0WKJTqaHzTACwAMITPjaEuz3OSpjaS6Z/squad.xml

**Comment by ins0** [comment]
I updated the paa conversation, maybe this help - try if this works better now. Feel free to open this issue again.
