### ISSUE TITLE
24TH.TMT

### ISSUE THREAD

**Issue by Jarrer** [ins0/armasquads#159]
![background_default_arma3](https://user-images.githubusercontent.com/34443306/33881357-83a741ec-df6f-11e7-9df2-5014429d6249.png)

![logo](https://user-images.githubusercontent.com/34443306/33881358-841d7592-df6f-11e7-85e0-ea0c67702290.png)

ckground_default_arma3](https://user-images.githubusercontent.com/34443306/33881357-83a741ec-df6f-11e7-9df2-5014429d6249.png)

![logo](https://user-images.githubusercontent.com/34443306/33881358-841d7592-df6f-11e7-85e0-ea0c67702290.png)

<?xml version="1.0"?>
<!DOCTYPE squad SYSTEM "squad.dtd">
<?xml-stylesheet href="squad.xsl?" type="text/xsl"?>

<squad nick="24TH.TMT">
<name>第24混成战术打击联队</name>
<email>2353187089@qq.com</email>
<web>http://www.24TH.TMT.com</web>
<picture>https://user-images.githubusercontent.com/34443306/33881358-841d7592-df6f-11e7-85e0-ea0c67702290.png</picture>
<title>Twenty-fourth mixed tactics strike United</title>
<member id="76561198192220330" nick="Baozi">
<name>Baozi</name>
<email>2293019693@qq.com</email>
<icq>2293019693</icq>
<remark>welcome to 24TH.TMT</remark>
</member>
<member id="76561198098583933" nick="Black.bird">
<name>Black.bird</name>
<email>969042612@qq.com</email>
<icq>969042612</icq>
<remark>welcome to 24TH.TMT</remark>
</member>
<member id="76561198156731902" nick="maoyu">
<name>maoyu</name>
<email>615904722@qq.com</email>
<icq>615904722</icq>
<remark>welcome to 24TH.TMT</remark>
</member>
<member id="76561198310847900" nick="Small">
<name>Small</name>
<email>1623934872@qq.com</email>
<icq>1623934872</icq>
<remark>welcome to 24TH.TMT</remark>
</member>
<member id="76561198068284931" nick="WuNian">
<name>WuNian</name>
<email>jarrer@163.com</email>
<icq>137194560</icq>
<remark>welcome to 24TH.TMT</remark>
</member>
</squad>

**Comment by ins0** [comment]
Feel free to open this issue again with more information.
