### ISSUE TITLE
Logo is not showing in Arma 3 Game

### ISSUE THREAD

**Issue by 4HCcrashh** [ins0/armasquads#163]
My squad name and motto appear in the game but the patch does not load. 

This is my URL.

http://armasquads.com/user/squads/xml/uHLCkmgJfgaeobndas1Yof6VKa1N4nws/squad.xml

As an experiment I had a squad that was working fine. I took the logo from the old squad and assigned it to this new squad.  It did not show up in game as well. 

Thank you for any assistance.

**Comment by 4HCcrashh** [comment]
If you need more donations you could start with response to issues we are posting?

**Comment by 4HCcrashh** [comment]
Old squad logo still works..  Any new versions of the logo or new squads created do not work.

**Comment by ins0** [comment]
I updated the paa conversation, maybe this help - try if this works better now. Feel free to open this issue again.
