### ISSUE TITLE
Where are the people in charge here?

### ISSUE THREAD

**Issue by 4HCcrashh** [ins0/armasquads#164]
Still no answers to questions posted in this forum concerning squad logos not working in Arma3.

Who is in charge here?

**Comment by ins0** [comment]
i am. most of the issues are "not working" questions without any information that helps to investigate the issue - as for proper investigation the server operator (where the logo is not showing up) musst provide debug information. without this, i can't do much about it as:

- bohemia provide rare information about using and providing squad xmld
- there are only a few debug information for server owners that helps to identify logo/xml issues

feel free to ask you question.
