### ISSUE TITLE
Geht nicht brauch support danke 

### ISSUE THREAD

**Issue by Bloodyharry** [ins0/armasquads#166]
moin moin habe probleme mit dem logo hab alles so gemacht wie gewonnt aber ich seh kein logo gar nichts kein clan name nichts kan mir einer weiter helfen danke im voraus    
http://armasquads.de/user/squads/xml/VG5OC7jMVg4wqNVex35l2SazxYB2SxZw/squad.xml
hab auch meine IP und alles bei meinem profil eingegeben

**Comment by ins0** [comment]
Without more information, i will close this. Feel free to reply and open this issue again.
