### ISSUE TITLE
The image logo do not show for me in game

### ISSUE THREAD

**Issue by Lanterna2000** [ins0/armasquads#171]
Hello guys
I'm having a problem creating my squadxml
I can complete the inscriptions until the abbreviation of the squad appear in my nickname within the game but does not appear the logo that I am loading on the site.
I already in the dimensions 64x64, 128x128 and 256x256 and do not appear.
Can someone help me?

**Comment by EM-Creations** [comment]
I have the same issue..

**Comment by ins0** [comment]
maybe related to https://github.com/ins0/armasquads/issues/191
