### ISSUE TITLE
XML No longer Working.....

### ISSUE THREAD

**Issue by Reaptard** [ins0/armasquads#172]
So I made an image that met the requirements, successfully uploaded it. Added myself as a member, filled out the ID info, Added my in game profile name (Spelt exactly as in game) and the other details.  Launched  game, successfully loaded into my server and saw all the info and image on my character.

I then Noticed the "N/A" above the XML info, so i shut down my game and went back to the website and noticed i didn't fill out "Squad Title" i then made my changes and saved. Then relaunched Arma and now it will not work. I assumed that it would redownload and now a week later, My XML will not display on my profile. 

I triple checked my info in members section and nothing has change.  I then cleared my cache in my located in local files and relaunched game and no XML. I have deleted my squad and remade it 3 times, nothing. I have verified my game 2 times, nothing. But it works for the rest of my group, but not me. Short of reinstalling my game, I have tried everything i know.

If someone has a way to correct this it would be awesome.

Thank you

![image0](https://user-images.githubusercontent.com/43191904/45396692-be583e00-b5f1-11e8-9ccd-e4a504bbc5a8.jpg)

![image1](https://user-images.githubusercontent.com/43191904/45396694-c3b58880-b5f1-11e8-8d7d-5a4d1a8dfb22.jpg)

**Comment by Strike-Eagle** [comment]
same here, no longer working since yesterday, any idea why?

**Comment by Reaptard** [comment]
Open no idea, hoping someone here would be able to assist fixing the issue.

**Comment by ins0** [comment]
maybe related to https://github.com/ins0/armasquads/issues/191
