### ISSUE TITLE
Unable to submit creation request

### ISSUE THREAD

**Issue by 9th-TF** [ins0/armasquads#174]
![001](https://user-images.githubusercontent.com/50526599/57581262-8c340e80-74e7-11e9-846f-cbbe516a35b7.jpg)

**Comment by SirLagALot17** [comment]
Having the same issue could someone please find out why this is happening please.

**Comment by por-ter** [comment]
+1

**Comment by ins0** [comment]
Thanks for the Report guys, should be fixed! 👍
