### ISSUE TITLE
ArmaSquad doesnt work

### ISSUE THREAD

**Issue by raider99zz** [ins0/armasquads#179]
I created a squad and added members like normal, If i copy the XML link and paste it into my browser i get the error:

image size: 256pxx256px 

" An error occurred
An error occurred during execution; please try again later. " 

Also in Arma the XML isnt working. Is there a problem with ArmaSquad?

**Comment by ins0** [comment]
Thanks for letting me know. Fixed the error and should now work as intended. 👍
