### ISSUE TITLE
Problem squad

### ISSUE THREAD

**Issue by R353T** [ins0/armasquads#181]
Welcome.
 I have a problem displaying the squad in the game. After your update, it doesn't show me anything. I tried to start everything from scratch, but it doesn't work. Please help. Before, everything was ok.

**Comment by Aussie602** [comment]
Hi R353T I just have the same Problem 4 days now . Did you got a support nobody answer my mails

**Comment by ins0** [comment]
please look here https://github.com/ins0/armasquads/issues/182
