### ISSUE TITLE
Arma Squads ist not Working?

### ISSUE THREAD

**Issue by TheUsforcer** [ins0/armasquads#182]
The Site ist unavaible. 
Is Armasquads down, oder only an Issue?

Greetings

**Comment by Sheppard85oc** [comment]
I have it too, on my Linux Server dont worked more since days.

**Comment by ins0** [comment]
Please try and use `https` instead of `http` within your squad xml url. so please change

`http://armasquads....` to `https://armasquads....`

**Comment by Sheppard85oc** [comment]
I have it try and still used old link but replaced hattp -> to https and at the moment its dont work, Its something more maybe my link broken for my unit?

**Comment by ins0** [comment]
@Sheppard85oc are the complete squad details not shown ingame or just the logo?

**Comment by Sheppard85oc** [comment]
The complete squad details will not show. No Infos no Logo.

**Comment by Aussie602** [comment]
I am playing Arma 2 and I also have all this Problems i am not owner of a Server . I am just a user of it . I try all this http://   https://  also nothing ....It dosen't work anymore so what is the problem how we can fix it? Isit a problem of armasquad xml or a worldwide server problem after armasquad xml change server???? 
Is there an official statement from the owner of armqsquad xml out ??? Still no Infos.....very sad

**Comment by ins0** [comment]
> Is there an official statement from the owner of armqsquad xml out ??? Still no Infos.....very sad
i'm the owner of armasquads, so what statement do u want to hear?

@Sheppard85oc 
sry the stupid question but what is a unit server? i'm currently not playing arma so can u light me up? So the XML is showing when u run a locally server, but not online (your local is an unix debian system and the one where it wont work is a windows?

**Comment by Sheppard85oc** [comment]
@ins0 No you get it wrong i try it to make esay but my english its bad...so
With Unit Server i mean the Clan Server where i play (Milsim) and thats its a Linux Debian root server there its it not Work = No Logo and no Infos of that xml anymore to see since the New Server.

On my Local server (win 10) Arma -> Editor ->set Player -> start in MP Modus  there i can see all Infos and logo of the XML. = there Work it.

Unit Server = Mean i https://85th-operations-command.de/ -> my Arma Clan server.

**Comment by Aussie602** [comment]
@ins0   Marco ich möchte einfach wissen wo das Problem ist wir alle hier versuchen das und jenes nur das kann es ja nicht sein nichts funtzt. Es war alles ok bis Du den Server gewechselt hast seid dem sind die Probleme eben da. So wie auch alle anderen das mir bestätigen. Als Anwender verstellen wir machen neu achten auf das und jenes und es funktioniert nicht. Bezogen auf das Statement wollte ich nur das Du uns sagst nein es liegt nicht an "meinem" Server Ihr habt das Problem mit eurem Server oder was auch immer oder eben das Du das checken tust was es sein könnte und wir uns eben gedulden müssen. Bis Du das Problem gefunden / gelöst hast.
Sollte es nicht mehr gehen haben wir eben Pech gehabt war zwar eine schöne Sache aber dann ist das eben so, Sorry das alles in Deutsch ist bin gerade von der Arbeit gekommen und wollte nur schnell antworten

**Comment by Sheppard85oc** [comment]
Hello
I became interested in whether this is really an OS system problem or whether it is something different or whether this is due to the new server or the https thing and how its can be fixed.
@ins0 i see you are German too, is it allowed to write in German for Bug reports?

**Comment by ins0** [comment]
@Sheppard85oc sure thing.

https://feedback.bistudio.com/T80864
Looks like after 5 years someone from bohemia is investigating this issue

**Comment by Sheppard85oc** [comment]
Okay i will wait for that :D
