### ISSUE TITLE
Logo of squad missing in ARMA 2 OA 

### ISSUE THREAD

**Issue by Arkadiusszowski** [ins0/armasquads#191]
After editing squad name from RSOF to RSoF, or RSF - logo is visible on website, but not in ARMA

**Comment by ins0** [comment]
please give a sample of your logo file within an zip archive

**Comment by Arkadiusszowski** [comment]
Actually after few days it was fixed by itself, so i don't know should I still upload logo. Probably not. If you were reason of issue being fixed - thank you.

**Comment by ins0** [comment]
Indeed, i changed something. Can u please check what URL you are saved in your game profile for the logo? `https` or `http`?

**Comment by Arkadiusszowski** [comment]
Checked right now - i'm using https

**Comment by ins0** [comment]
Ok, it might be something with the https force on the armasquads website - the devs confirmed they fixed ssl for the logo  lookup request - but it sounds like that something is still messed up. Maybe some internal requests from the client still using http only. I will not revert the change i made, so i hope this will help. Thanks for the report - i will close this now.
