### ISSUE TITLE
Duplicate Users are not handled properly

### ISSUE THREAD

**Issue by YoYo-Pete** [ins0/armasquads#26]
I had two arma profiles... 'YoYo-Pete' and 'YoYoPete'   The second because Breaking Point did not like the hyphen.

I thought 'oh.. I will just add both to the roster with the same player ID, allowing the name to dictate the user'.  This way I would show in squad no matter which profile was used.

Your site does not allow duplicate Player IDs to be added to the same squad.  The issue is there is no error handeling for it.  It threw some odd error and loaded the page inside of the current page, and it just got a bit wonky.

I dont know if Arma would support that or not as I never had my own XML to test with.     I'm curious, but at this point I've dropped the name with the hyphen so I didnt worry about it.     Maybe I will test the duplicate player ID with different profile names in an XML tonight when I test adding extra fields into it as I wanted to know if that would work.

If it does work, you might want to allow for duplicate player IDs in the same squad as long as the name is different.   I'll report back with findings just so we both know.

**Comment by ins0** [comment]
fixed
