### ISSUE TITLE
Logo don't show up arma 2

### ISSUE THREAD

**Issue by xxdervishxx** [ins0/armasquads#33]
http://armasquads.com/user/squads/xml/MCdcYWFzDr9u2jffg5LD6CIzsHE0ndut/squad.xml
logo don't show up.

**Comment by Boy1991** [comment]
http://armasquads.com/user/squads/xml/HjXYAHYtzxgktFxPEUSmidnMXWL3xFbZ/squad.xml
logo don't show up.
player id is right arma 2  I can see squad info on everyone from squad but we can't only see the logo
I need your help.

Logo>>> http://upic.me/show/54158106 <<<265*265

thankyou
