### ISSUE TITLE
Can't join a member

### ISSUE THREAD

**Issue by Holibu** [ins0/armasquads#37]
Hi, We are 11 members in my squad and there is one that i can't never add. The others there is no problem with them, it is only with this user:

PlayerID: 76561198016364752
Name: fabaluco

When I put an incorrect PlayerID or one for another player, it works, but if I put his correct ID, when I click on save, it appears a page with the message "Wwwooooppss! 404 Page not found"

My squad is http://armasquads.com/user/squads/xml/R6xI10MnpXM9YLi1fYJHTYVzJ8Eh8RUj/squad.xml

Can you help me please?

Thanks in advance.

**Comment by ins0** [comment]
fixed
