### ISSUE TITLE
logo don't show up.I need your help.thankyou

### ISSUE THREAD

**Issue by Boy1991** [ins0/armasquads#38]
hello i have the same problem Logo don't show
 http://armasquads.com/user/squads/xml/HjXYAHYtzxgktFxPEUSmidnMXWL3xFbZ/squad.xml
logo don't show up.
player id is right arma 2 I can see squad info on everyone from squad but we can't only see the logo
I need your help.

Logo>>> http://upic.me/show/54158106 <<<265*265

thankyou

**Comment by ins0** [comment]
please test your logo with a nick without an underscore in your nick
``Boy_Bbk`` => ``BoyBbk``

**Comment by Boy1991** [comment]
I do as you say. "BoyBbk" I can see squad info  but logo don't show sir.

**Comment by Boy1991** [comment]
@ins0   I do as you say. "BoyBbk" I can see squad info but logo don't show sir.

**Comment by Boy1991** [comment]
@ins0 thankyou sir

**Comment by ins0** [comment]
Is your problem solved?

**Comment by Boy1991** [comment]
arma 2 how much full Sites sir ???

**Comment by ins0** [comment]
what?

**Comment by Boy1991** [comment]
please modify photograph NEW LOGO 

>>> http://upic.me/show/54169230 <<< 256*256 

thankyou sir

**Comment by Boy1991** [comment]
http://armasquads.com/user/squads/xml/HjXYAHYtzxgktFxPEUSmidnMXWL3xFbZ/squad.xml

**Comment by Boy1991** [comment]
please View pic me >>>>>>>>  http://upic.me/show/54169458

**Comment by Boy1991** [comment]
I need your help.

Logo>>> http://upic.me/show/54169230 <<<265*265

thankyou

**Comment by Boy1991** [comment]
Thanks for everything. succeed  My Squads

**Comment by Boy1991** [comment]
@ins0  Thanks for everything. succeed My Squads
