### ISSUE TITLE
The squad TAG is on the right side of the name.

### ISSUE THREAD

**Issue by RicardoRazz** [ins0/armasquads#39]
Hi,
Is there any chance of having the squad TAG on the left side of the name like : [TAG] player.
Right now the tag is on the right side.

Thank you very much,
PS: If you guys need any help on the development of this project please let me know. I would be glad to help out.

**Comment by ins0** [comment]
i'm currently the only one that develops this project. don't know what your issue is - because the game itself or the server mod handle how the squad tag + name are displayed and currently this is ``[TAG] Playername``
