### ISSUE TITLE
Sizing

### ISSUE THREAD

**Issue by MrTaugs** [ins0/armasquads#40]
No matter what size i convert my image. It still wont upload. Need help please.
![taugs oil](https://cloud.githubusercontent.com/assets/10466143/5683256/9417a00c-97e3-11e4-8a54-eac32afe6887.png)

**Comment by MrTaugs** [comment]
Keep getting this error

Error

Upload a logo in one of the following dimensions: 16x16/32x32/64x64/128x128/256x256

**Comment by ins0** [comment]
![logo](https://cloud.githubusercontent.com/assets/2622534/5684244/e300c89c-982e-11e4-9279-03c70265e12d.png) try this

**Comment by MrTaugs** [comment]
I have no idea what you did. But it worked. Thank you so much. I've been doing XML's for a while but never ran into this issue. What did you do?

**Comment by ins0** [comment]
resized the image to 256x256 :)

**Comment by MrTaugs** [comment]
Ok, thats weird. any conversion sites i used said it did it. but no go.
