### ISSUE TITLE
Add support of Cyrillics

### ISSUE THREAD

**Issue by MacMillan11** [ins0/armasquads#42]
Add support of Cyrillics.

**Comment by ins0** [comment]
cyrillics are supported by the site but i don't think arma will display it

**Comment by MacMillan11** [comment]
Thank you very much! Everything works! Simply I remember that several months ago the site didn't support the Russian symbols.

**Comment by ins0** [comment]
yeah that is correct, a user informed me before #36 - but thanks for your feedback! :+1:
