### ISSUE TITLE
Information and Logo dosent show up

### ISSUE THREAD

**Issue by ZimZooM3** [ins0/armasquads#43]
So I play on this Altis Server and I wanted to make a Squad XML for my gang I do A LOT of Squad XMLs but this one I couldnt figure out how to fix anyways I did everything as usually BUT Arma Logic dosent want me get it working so I hope you'll help me out here
P.S:Already tried to create the Squad XML again it didnt work
![8ca33b8238fd8becec7d3061c85c8327](https://cloud.githubusercontent.com/assets/10524239/5732518/d3f3320c-9b9b-11e4-81c5-df2a39a840db.png)

My Squad XML:
http://armasquads.com/user/squads/xml/xgTMPI8SIFgeRp18rHq9mpOXZ4YjahFE/squad.xml
![2015-01-14_00001](https://cloud.githubusercontent.com/assets/10524239/5732479/22ec34fe-9b9b-11e4-951b-780458cd4aca.jpg)

**Comment by ins0** [comment]
sry for my late response, is your problem fixed?

**Comment by soulgamerhd** [comment]
I've the same Problem

**Comment by ins0** [comment]
@soulgamerhd please be more specific of your problem and provide your squad xml and infos

**Comment by soulgamerhd** [comment]
Ok ! I can see the Squad on all Servers expect of my Arma 3 Altis-Life Server

**Comment by ins0** [comment]
so your squad xml is working on all other servers except your own server?

**Comment by soulgamerhd** [comment]
Yes :/

**Comment by ins0** [comment]
hhmm nothing i can do right now as it seems there is a problem with your server and not the xml itself.

linux server?

**Comment by soulgamerhd** [comment]
No Arma is only Running on Windows

**Comment by ins0** [comment]
your server needs access to port 80,8080 and 443 in order to download a squad xml when a player is joining your server, please check if the ports are allowed by your server firewall.

**Comment by soulgamerhd** [comment]
Hmmmm, I'm hosting the server at Nitrado and on my previous Server everything was Shown. And now not :/

**Comment by STONEY-DSP** [comment]
@ soulgamerhd,  as far as i know and have heard and experienced (as gamer on all the Nitrado servers i went incl.wasteland life and Co-op the squad.xml shows sometimes but moste of the time not) ) with Nitrado is that their servers alway's had problems and could still even have problems with the squad.xml files. They have a FAQ section; https://server.nitrado.net/dut/pages/support/  might want to go there and ask it maybe Nitrado needs to do something from there side

**Comment by ins0** [comment]
@ZimZooM3 closing duo inactivity - please feel free to reopen
