### ISSUE TITLE
New Member?

### ISSUE THREAD

**Issue by Yatheria** [ins0/armasquads#44]
Hey guys,

i want to set up new members, but what ever we try, we can't get them in. They have the right URL, the right ID and so on. We don't know what to do. Someone any idea?

**Comment by ins0** [comment]
hey yatheria please be more specific what does not work

**Comment by Yatheria** [comment]
They can't join the squad. When they login, they doesnt have the logo and so on. But the other 6 of us don't have any problems

**Comment by ins0** [comment]
this makes no sense if the other 6 member have no problem and indicates an error by the guys wo trys to join. as they gives u the nicknames and uids, double check if the nicks and ids are 100% correct.

**Comment by Yatheria** [comment]
They are correct, thats the problem

**Comment by Yatheria** [comment]
We can't add a new member. The ID is correct, name is correct everything is fine, but they are not in the squad in arma...

**Comment by ins0** [comment]
can't add the member on armasquads.com in your squad?

**Comment by Yatheria** [comment]
No. I can add him there but it will not display in the game

**Comment by ins0** [comment]
please link your squad xml

**Comment by Yatheria** [comment]
http://armasquads.de/user/squads/xml/yoA5nnPuxDUvY5FoIcB2DroWSWnoGOX3/squad.xml

Thats from the squad. To test it, i created a second with the guys where it doesnt work:
http://armasquads.de/user/squads/xml/loIvNld6gQ17JVIZQYN8RkuDJz0njYoN/squad.xml

**Comment by Yatheria** [comment]
Any idea?

**Comment by ins0** [comment]
sry @Yatheria can find an error by the side eg. reproduce your error so this should be an error from the client side
