### ISSUE TITLE
Squad XML - not showing on server despite working previous day

### ISSUE THREAD

**Issue by AlexManta** [ins0/armasquads#45]
Hi!

Some of our members have told me that the Squad XML is not working on the servers they are playing despite it working in previous days. It seems other groups have their Squad XML working but they might be hosted by armasquads.com. 

If you need anymore info, let me know. Thanks for the awesome service!

**Comment by ins0** [comment]
can u please give more information with long your squad xml url?

**Comment by ins0** [comment]
@AlexManta closing duo inactivity - please feel free to reopen
