### ISSUE TITLE
No password revovery

### ISSUE THREAD

**Issue by doGfoodliD** [ins0/armasquads#46]
I made an account but there seems to be no password recovery process

**Comment by ins0** [comment]
i will send u a new password - after login change it please under your account settings

**Comment by doGfoodliD** [comment]
Ok i will do that as soon as the email come through and thank you

**Comment by ins0** [comment]
mail is out

**Comment by Leviat1001** [comment]
i lost too can you help me?

**Comment by ins0** [comment]
@Leviat1001 please send me an email from your registered account email to ``ins0@racecore.de`` i will send you afterwards the temporary account password

**Comment by Marco112** [comment]
wann wird die Passwort zurücksetzfunktion fertig sein ?

**Comment by velvetelvis77** [comment]
Hi ins0, been using armasquads for quite some time now, very satisfied, however I need help as to the recovery of my password, sent you an email earlier about account details such as email used for registration and squad name. Thank you and best regards.

**Comment by EvilAnimal** [comment]
I'm having the same issue. I tried to open a new account using the same email address and the new account will not work. If you see two accounts with my email and we can reset the password on the old account then just delete the new account please.
