### ISSUE TITLE
everything except picture is working

### ISSUE THREAD

**Issue by LawsOfFire** [ins0/armasquads#47]
as the title says. everything i entered works great. but the picture does not.

i tested it on multiple servers

**Comment by ins0** [comment]
please provide your squad xml

**Comment by LawsOfFire** [comment]
http://armasquads.com/user/squads/xml/tDZT82KHZHbWXt76hdpFJqKkHZnFBR2h/squad.xml

**Comment by ins0** [comment]
please upload a new logo as long your squad.xml says "......png" in image there was an error converting your logo, re-upload check xml -> ".....paa" success if this wont work open your image in photoshop and re-save as your image us corrupted on meta level

**Comment by ins0** [comment]
just saw you reuploaded and still not working i fixed it by converting the image through photoshop in a clean format. give it a try now

**Comment by LawsOfFire** [comment]
well i re-reuploaded it. so you might have to do it again...

will check first

**Comment by ins0** [comment]
replaced give it a try

**Comment by LawsOfFire** [comment]
it's working now! thanks for being so quick to help.

**Comment by ins0** [comment]
you're welcome ;) have fun
