### ISSUE TITLE
Image not load

### ISSUE THREAD

**Issue by Veiamiope** [ins0/armasquads#48]
Hi, 

I mounted a successful squad. the information load perfectly in game, but the image of the logo will not appear in the game. The image appears only in Armasquad site.
 I tried various shapes and sizes, is currently the lowest, 256x256, transparent gif and two-color B & W and still does not work. could help me?

 My nick is Veiamiope, 
».:URV:.« União de Rips e Viets
clanurv@gmail.com

Thanks a lot

**Comment by ins0** [comment]
please avoid special characters in your squad tag like ``.`` or ``:`` and test it without these.

**Comment by Veiamiope** [comment]
Thank you for your response.

 I did the Exchange Tag, but still the logo will not appear in the game, only the information that is on the site.

 Is there a recommended format for this logo?

Tks!

**Comment by ins0** [comment]
i lookup your logo and it seem there was an error converting your image as it only contains 2 colors, even by hand i can't convert your logo to the ``paa`` logo format for arma. so you need to upload a different one. sry about that but there is nothing i can do

**Comment by Veiamiope** [comment]
Very Good! I changed the image for a larger format and it worked this time!

 Thank you and congratulations on your excellent work.

**Comment by ins0** [comment]
:+1: thanks
