### ISSUE TITLE
Logo does not show up

### ISSUE THREAD

**Issue by Kruemmel** [ins0/armasquads#49]
Our Squadurl shows all information but the jpg/png is not to see. When we get in a car only the Title is on the car but no Icon. 
Ports and everything is okay because the other urls work 100%. 

our URL is: http://armasquads.de/user/squads/xml/Jotc5QeYTzAamM6DNAZBKdJiBwZwMLGr/squad.xml

**Comment by ins0** [comment]
Please reduce yor squad tag and remove all special characters.
arma have stange behaviors if you have special charaters in your squad tag

**Comment by Kruemmel** [comment]
Nope didnt Help. Deleted everything and did it new. No Pic ingame :/

**Comment by ins0** [comment]
still special characters in your squad tag ``*``

**Comment by Kruemmel** [comment]
Ah okay.

Thank you for your fast Help :) :+1:

**Comment by ins0** [comment]
:+1: you're welcome
