### ISSUE TITLE
My clan symbol doesnt show up ingame

### ISSUE THREAD

**Issue by OAL99** [ins0/armasquads#50]
Hey,
so i made an clan with your website, and with the link that i got i pasted it in to my profile, but my symbol doesnt show up on my sleeves ingame. What have i done wrong?

**Comment by ins0** [comment]
https://github.com/ins0/armasquads/issues?q=is%3Aissue+is%3Aclosed+label%3A%22squad+logo%22

**Comment by ins0** [comment]
closing duo inactivity - please feel free to reopen
