### ISSUE TITLE
Squad Logo Not Showing Up

### ISSUE THREAD

**Issue by NoNamesLeftJoe** [ins0/armasquads#51]
Sorry but I am another one that cannot get clan tags to show in game.  I spent about 5 hours resaving various pictures in jpg, jpeg, and png formats.  All pictures were saved as 256x256 size.  All images upload and yield successful conversion.  Squad tags are simple 2 and 3 letters - no special characters.  I can successfully create, edit and add members.  Steam ID is correct also for members.  I really did try many different combinations and resaved pictures with several different photo programs.  This post is my last resort.

Here are three urls I tried but don't work in game...that is...the graphic doesnt show in game on vehicles, etc.

These urls don't seem to work:

http://armasquads.com/user/squads/xml/70eTiix29LpRFOgL8xOLyihvaxtE1ZAV/squad.xml
http://armasquads.com/user/squads/xml/LsPjFjhcHOr3JAF77zxznVUL2gl6WRHZ/squad.xml
http://armasquads.com/user/squads/xml/LNHo8WoraWamWNeEnGMocmxuBBFefcdx/squad.xml
http://armasquads.com/user/squads/xml/5DHiyNe90C1a3J2fdK1qWuOB2oTTjOWZ/squad.xml
http://armasquads.com/user/squads/xml/pVgw63gFrHx3HVLc0OcwTZnSFEbD04BZ/squad.xml

My friend used one of the same picture files (png) with same and settings and created a clan tag that works in game with this url:

http://armasquads.com/user/squads/xml/jCpF1vQhXu4viMk7yVZZQm7TAtDxglkb/squad.xml

Thank you in advance for any solutions you may have.  My armasquads account name is the same NoNamesLeftJoe.

**Comment by ins0** [comment]
i can't test ingame so did u allready tried to fill out the same details as your friend where the logo works?

**Comment by NoNamesLeftJoe** [comment]
yes


On Wed, Feb 25, 2015 at 4:11 PM, Marco Rieger <notifications@github.com>
wrote:

> i can't test ingame so did u allready tried to fill out the same details
> as your friend where the logo works?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ins0/armasquads/issues/51#issuecomment-76059691>.
>



-- 
Joe

**Comment by NoNamesLeftJoe** [comment]
The only thing I can think of the url is giving me incorrect directory
perhaps?

On Wed, Feb 25, 2015 at 5:32 PM, NoNamesLeftJoe <nonamesleftjoe@gmail.com>
wrote:

> yes
>
>
> On Wed, Feb 25, 2015 at 4:11 PM, Marco Rieger <notifications@github.com>
> wrote:
>
>> i can't test ingame so did u allready tried to fill out the same details
>> as your friend where the logo works?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ins0/armasquads/issues/51#issuecomment-76059691>.
>>
>
>
>
> --
> Joe
>



-- 
Joe

**Comment by NoNamesLeftJoe** [comment]
Yes on the last two with no members - I recently removed myself as a member but testing the files had same result
