### ISSUE TITLE
Clan image does not appear in Arma3

### ISSUE THREAD

**Issue by StairusOSX** [ins0/armasquads#52]
in theory it should be fine, but does not appear

mi squad: http://armasquads.com/user/squads/xml/dvwSROZyxkI76jsoTYQARNZpgH0bZrKn/squad.xml

**Comment by Danipredato** [comment]
the picture is paa file make it a jph or png it should work

**Comment by kripto202** [comment]
how squad xml works is that you need to make sure that everyone is using the same exact name in the squad xml. If not, the profile and picture won't come up.

**Comment by ins0** [comment]
closing - feel free to reopen if there are still questions open
