### ISSUE TITLE
Squad logo doesn't show up in ARMA 3

### ISSUE THREAD

**Issue by ElyziumIV** [ins0/armasquads#53]
Could you please check our new logo as it will not show up ingame or when downloading the zipfile from this site.
The old logo worked and I can't see whats wrong with the new one.
Have tried different image formats and nothing ingame but I can see it here on our squad page.

Thanks!

**Comment by ins0** [comment]
you logo could not be converted to the ``.paa`` file format - as in the xml is the logo file type ``png`` please provide a different logo which is not broken or invalid saved on your computer.

**Comment by ElyziumIV** [comment]
Yeah its strange. Worked with ARMA 3 tools.
Got another image now online, thanks for your help.
