### ISSUE TITLE
Squad Logo and info not showing

### ISSUE THREAD

**Issue by Mantiamd** [ins0/armasquads#55]
http://armasquads.com/user/squads/xml/dWMib4dJigaoR1srpjpjhQ9JOkT98ik9/squad.xml

The "motto" shows up but the information and logo do not.

**Comment by ins0** [comment]
edit your squad xml and remove all special characters and test if again - note that squad logos currently not working when connecting to linux gameservers.

http://feedback.arma3.com/view.php?id=22506

**Comment by Mantiamd** [comment]
what special characters?  Does "-" count as a special character?

On Fri, Mar 13, 2015 at 3:17 AM, Marco Rieger <notifications@github.com>
wrote:

> edit your squad xml and remove all special characters and test if again -
> note that squad logos currently not working when connecting to linux
> gameservers.
>
> http://feedback.arma3.com/view.php?id=22506
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ins0/armasquads/issues/55#issuecomment-78844752>.
>



-- 
* Michael Mantia **
<http://www.linkedin.com/profile/view?id=232346071&trk=hb_tab_pro_top>*

*Mobile (937)830-0807                            *

**Comment by ins0** [comment]
can't give you a full list as bohemia don't give any detailed informations on this but everything excepts ``a-z A-Z 0-9`` can cause problems

**Comment by Empclan** [comment]
http://armasquads.com/user/squads/xml/m6wA7iRD7l2k8qwse5sVQB9rnAlArinT/squad.xml
I also am having this problem with some of our squad members only show partial information or none at all.

**Comment by ins0** [comment]
>can't give you a full list as bohemia don't give any detailed informations on this but everything excepts a-z A-Z 0-9 can cause problems

**Comment by ins0** [comment]
closing - feel free to reopen if there are still questions open
