### ISSUE TITLE
Squad XML - Everything works but squad logo not showing on ANY Server - 

### ISSUE THREAD

**Issue by AustralianInfidel** [ins0/armasquads#56]
http://armasquads.com/user/squads/xml/gNAY4SNfV5Fl1O1ryZYDqRZ1yFzeTzFN/squad.xml

All information displays correctly ingame other than logo. Logo does not display ingame or in player list.

Any ideas?

**Comment by ElyziumIV** [comment]
Same for me as in my ticket.
Please let me know if you find any solutions.
Thanks.

**Comment by ins0** [comment]
squad xml looks fine - so maybe the pasted link in your profile is corrupt when the xml is not recognized on any server

**Comment by AustralianInfidel** [comment]
Hi m8. Apologies for misunderstanding the instructions.
Can you please explain step by step ( <-- idiot here.. tried a few times and i know i am just not getting it ) on what the image requirements are.

Ive done .paa   and .jpg.

Made the images 256 * 256 pixels.      I understand i am doing it wrong. But not sure how.

Thank you for your assistance

**Comment by AustralianInfidel** [comment]
Also. Deleted the squad xml. created a new one. http://armasquads.com/user/squads/xml/kr1v28YWyFvpvfXYYIkuoeTL3mLyu0Hh/squad.xml

Added myself as member.

Still same issue. Any advice would be great

**Comment by biowire20** [comment]
Nasty bug i have to report that is a huge problem but saw this and had to comment to help you immediatly "ins0" please get this on your website for typing squad nickname you can not have "." a period in your squad nickname it will make your pic invisible i just solved this issue and it worked, if your squad nickname is "w.s.c.' you must make it "wsc" if you want your logo to work.

**Comment by ins0** [comment]
closing - feel free to reopen if there are still questions open
