### ISSUE TITLE
Problem upload .paa squad logo

### ISSUE THREAD

**Issue by GEFSQUAD** [ins0/armasquads#57]
I uploadet a picture on the squad, but its not working and i know why, because png. Now i tried to convert the png to paa with TexView 2, i cant upload it now.. the paa picture is now a white empty file not possible to upload... i hope you understand what i mean.. please help

here my squad site http://armasquads.de/user/squads/xml/kqqI16ef6r74HDG2r3lQi2X1oS3c2kiK/squad.xml

**Comment by ins0** [comment]
i don't know why but arma don't like images with less then 3 or 5 colors - don't ask me why but if you upload a more detailed picture (more colours) your image should be converted without an error.

**Comment by GEFSQUAD** [comment]
allright, thank you for answer.

**Comment by ins0** [comment]
you're welcome, please let me know if your problem is solved

**Comment by GEFSQUAD** [comment]
now i got solved the problem with the error on texview 2, but now on the squad site cames the message if i try to uploade the file : you only can upload logo with png,jpg,jpeg,gif

**Comment by GEFSQUAD** [comment]
problem solved thank you very much, please close

**Comment by ins0** [comment]
:+1:
