### ISSUE TITLE
squad info plus logo  doesnt work

### ISSUE THREAD

**Issue by dvdbrewster** [ins0/armasquads#58]
my squad xml works on my friends game. It does not  work with mine. I tried filling in all the blanks..
I removed the brackets from my clan tag, removed the title, wrote my ingame name in the name field
(squad name?)(friends game everything works.)  I joined the squad and triple checked the player id.
and triple checked the xml line in the profile editing..   I don't Know  what to do next.
I click the files in the folder I downloaded and they look complete.
http://armasquads.com/user/squads/xml/wAdW1SX6gC0LUXMmDpsQKsb26eXplH4k/squad.xml
I even  gave 10 dollars.    Is there  a game file I can enter it manually?          dvd

**Comment by ins0** [comment]
hey @dvdbrewster can u please be more specific what doesn't work?
- your complete squad info is not visible ingame
- only your squad logo doesn't work

**Comment by dvdbrewster** [comment]
Nothing is visible ingame  on my profile/computer.   "0"

**Comment by ins0** [comment]
can u please make sure and blank the squad url field in your arma profile and copy & paste the url new only to make sure there is no issue there - so your squad xml is never requested from servers

**Comment by dvdbrewster** [comment]
BRB

**Comment by dvdbrewster** [comment]
The paste function does not work for the edit profile window.

**Comment by ins0** [comment]
arma3?

**Comment by dvdbrewster** [comment]
yes.  I just tried it. Copied from armasquads .com  and it wont past to the url field in profile editor

**Comment by dvdbrewster** [comment]
Is there a keyboard shortcut to do paste ?

**Comment by ins0** [comment]
then there is some issue on your side with the copy & paste works on my pc - please make sure the url pasted or entered in your profile is clean

**Comment by ins0** [comment]
STG + V = paste
STRG + C = copy selected text

**Comment by ins0** [comment]
just looked up the access log for your squad xml - confirmed your squad xml was never requested from any gameserver so there is a issue in your profile xml url.

**Comment by dvdbrewster** [comment]
the keys worked..

**Comment by ins0** [comment]
request from a gameserver just now ``
XXXX - - [28/Mar/2015:23:03:58 +0100] "GET /user/squads/xml/wAdW1SX6gC0LUXMmDpsQKsb26eXplH4k/squad.xml HTTP/1.1" 200 428 "-" "BIGameEngine"
XXXX - - [28/Mar/2015:23:03:58 +0100] "GET /user/squads/xml/wAdW1SX6gC0LUXMmDpsQKsb26eXplH4k/d647ba613691cf6b85df53bde6f7eee8.paa HTTP/1.1" 200 11080 "-" "BIGameEngine"``

**Comment by dvdbrewster** [comment]
That was it all the time..  I was even looking at some troubles of javascript instead of inicode 8.
U fixed it..

**Comment by ins0** [comment]
@dvdbrewster nice to hear that it is now fixed - have fun :+1:

**Comment by dvdbrewster** [comment]
so they still ask for it.. Is that BAD ?

**Comment by ins0** [comment]
what?

**Comment by dvdbrewster** [comment]
the servers request this normal?

**Comment by ins0** [comment]
yeah if you connect to a server the gameserver request your squad url from your profile and armasquads.com deliver this squad xml - then the server process the xml file and show the content ingame (clan tag - squad logo etc.) so the requests i posted above show a gameserver that requests your xml - which means your xml url in your profile is correct :)

**Comment by dvdbrewster** [comment]
awesome
