### ISSUE TITLE
Site Broken

### ISSUE THREAD

**Issue by Bbobbai** [ins0/armasquads#59]
Site seem to be zoomed into one side. Broken, screens below.

http://gyazo.com/967c24ba95207a68962fe9ef694e9da7

**Comment by imthatguyhere** [comment]
http://i.imgur.com/dPhv1Bq.png

Same here. All pages. Firefox 36.0.4 and 37.0.1

http://i.imgur.com/1OCkkei.png

That's the latest 2  versions of chrome.

**Comment by ins0** [comment]
@Bbobbai what browser + version do you use?

@imthatguyhere just checked against 37.0.1 site looks good - so i can't reproduce the error on a clean firefox version. can you please clear your cache and try it again?

just jumped on the last version of bootstrap may this fix the layout issues?!

**Comment by ins0** [comment]
sry for this reference horror - @Bbobbai @imthatguyhere can you please test if the site now works for you guys?

the problem occurs only if you had adblock software installed and as the ads are now part of the layout if they gets removed (by the adblock) the page was messed up. should be working now with adblock enabled.

**Comment by kripto202** [comment]
the sight is down or some error is stopping me

**Comment by ins0** [comment]
yeah give me a sec

**Comment by ins0** [comment]
should be working now thanks @kripto202

**Comment by imthatguyhere** [comment]
Works, http://i.imgur.com/hWZL8WN.png Oddly enough I didn't have adguard enabled and I still lack any adds so who knows. I just removed the classes and used it as normal anyway. Thanks for fixing it!

**Comment by ins0** [comment]
@imthatguyhere thanks for notifying me
