### ISSUE TITLE
Squad logo doesn't show up on vehicles or soldiers

### ISSUE THREAD

**Issue by Alexsys** [ins0/armasquads#61]
As the title says it doesn't show up
http://armasquads.com/user/squads/xml/nbvk8kOMc1CCH71CxB7aPa15UnFzh3ko/squad.xml

**Comment by ins0** [comment]
Other semilar questions:

- The board in my car shows a red light - what is that?
- My laptop won't boot - how can i fix that?

if you don't see any conection with your question above and don't know how to improve it with more information. What have you tried? What steps do you take from creating a squad xml on side within ingame...follow the instructions from prev. issues here - https://github.com/ins0/armasquads/issues?q=is%3Aopen+is%3Aissue+label%3A%22squad+logo%22?....and so on. if not then i can't help.

**Comment by ins0** [comment]
closing - feel free to reopen if there are still questions open
