### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jus61** [ins0/armasquads#63]
Hallo

Kann mir eventuell jemand bei der Installation helfen? 
Mein Webspace Anbieter ist all-inkl.com

Error:
Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to load ZF2. Run `php composer.phar install` or define a ZF2_PATH environment variable.

**Comment by ins0** [comment]
du musst mit ``composer install`` das vendor verzeichnis laden, da das projekt auf verschiedene libraries aufbaut.

**Comment by ins0** [comment]
closing - feel free to reopen if there are still questions open
