### ISSUE TITLE
Squads cease to work after ARMA update 1.44

### ISSUE THREAD

**Issue by vadklop** [ins0/armasquads#67]
Hello comrades its new problem there. After 1.44 update clan information dont work completly. Before 1.44 I had my xml file on Dropbox and everything work just great, but after update everything broke, but some clans which have xml file on their own web sites work like usual. I made my squad on armasquads.com in hope that on web site everything will be OK, but there a same problem.
 I write every data of memeber correctly, but in game function of Squads just not work.

**Comment by ins0** [comment]
can you please share the urls to working and none working versions of these xml files and in which version of arma the work/not work, please?

**Comment by vadklop** [comment]
I can show the xml of my squad, but cant show other, because I dont have them, well mabe I could ask for some xml from Clan leaders but I think nobody give me it.
 My xml always (from release of Arma 3 to 1.44) was in Dropbox, but after 1.44 update for Arma 3 everything is broke.
 I noticed that very much clans dont have any information about Squad in game anymore (In Russia at least).
 My squad (this xml not work too) - http://armasquads.com/user/squads/xml/hHc3PAjLLmUi5Ax2rvdAHlJegzfjGtxR/squad.xml

**Comment by vadklop** [comment]
That xml is working https://drive.google.com/file/d/0ByUwUQTBv-1peW9Bb2hkZkNxam8/view

**Comment by ins0** [comment]
what arma version is currently installed on the server?

**Comment by vadklop** [comment]
I always check on my local server from my PC on Windows, and some servers on 1.44 and Windows all too.

I ask one man which xml is working (xml above), he said he have xml on his own FTP server. For test I ask to place my xml on his server, but it still not work, I dont know what to do, a paste the url correctly, cache of ARMA 3 is OK.

Looks like it my problem, but xml not working for all my teammates for my squad.

**Comment by ins0** [comment]
hard to say what issue is there as arma give no information at all to debug any kind of trouble with squad xml files.

currently i can't do anything except give some information and suggestions...hmm this sucks balls, everytime someone report a problem i don't know if it is my mistake or arma.

**Comment by ins0** [comment]
closing this if - feel free to reopen if there are still open questions
