### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by 93Reaper** [ins0/armasquads#71]
Hello, I noticed there is no way to recover my password, could you please send me a new one? Greetings Reaper

**Comment by ins0** [comment]
@93Reaper sry for my late response, do u need still a new password?

**Comment by 93Reaper** [comment]
No problem, you sended me a new one already, thanks :)

Date: Sat, 30 May 2015 21:56:12 -0700

**Comment by ins0** [comment]
Thanks wasn't sure if i allready send you a new password :)
