### ISSUE TITLE
Cant remove Squadmember

### ISSUE THREAD

**Issue by TheUsforcer** [ins0/armasquads#72]
I want to delete some Member of my Memberlist with the deletebutton, but if i go to menu -> squads there are already 8 members ob 8. I klick of "Members" and the deleten Members are back in the Memberlist.

**Comment by ins0** [comment]
will check this ASAP

**Comment by TheUsforcer** [comment]
Thanks

**Comment by ins0** [comment]
@TheUsforcer just fixed some stuff can you please confirm that your bug is fixed?

**Comment by TheUsforcer** [comment]
Jes, its fixed. Thank you

**Comment by ins0** [comment]
@TheUsforcer thanks you!
