### ISSUE TITLE
Logo doesn't change

### ISSUE THREAD

**Issue by TheUsforcer** [ins0/armasquads#74]
If i change the Logo of the Squad, the Logo doesnt change ingame.I restart arma but no logo

**Comment by ins0** [comment]
the logo show up after restarting arma or is not displayed?

**Comment by TheUsforcer** [comment]
The old ist not displayed but the new ist not displayed too

**Comment by ins0** [comment]
please provide a link to your xml

**Comment by TheUsforcer** [comment]
http://armasquads.de/user/squads/xml/9AAHpr2yBj5NW1I35nXFkhRp257joAAL/squad.xml

**Comment by ins0** [comment]
low color image, plrease test a different logo/image as logo and test if this works. sometime - idk why - arma refuses low color images

**Comment by TheUsforcer** [comment]
Doesn't work

**Comment by ins0** [comment]
what image did u tested?

**Comment by TheUsforcer** [comment]
the same with a low color image now i try the old one

**Comment by TheUsforcer** [comment]
the old one doesn't work anymore

**Comment by ins0** [comment]
use this logo for the test, if it works it is your logo. http://www.w3.org/MarkUp/Test/xhtml-print/20050519/tests/jpeg444.jpg 

can't do anything as the xml is correct and the logo in ``paa`` file format, everything else is in the hands of bohemia interactive

**Comment by TheUsforcer** [comment]
ok that logo works

**Comment by ins0** [comment]
the problem is that there are no information on file level of a valid ``paa`` file so i can't analyse why some images work and some other won't display at all.

**Comment by TheUsforcer** [comment]
ok

**Comment by TheUsforcer** [comment]
now the logo i would change works

**Comment by ins0** [comment]
which?

**Comment by TheUsforcer** [comment]
the logo that doesnt work first.

**Comment by ins0** [comment]
hhm strange i really don't know what cause this bug and is it buggy on my side or the arma 3 client. :confused:

**Comment by ins0** [comment]
finally something i can work with - thanks @TheUsforcer 

the first paa image you provide looks exactly the same as the working new one when viewing it with textview - same logo.

but on the bitwise level the logos are not equal - the paa file that is not working is missing one midmap 2x2 image. currently i don't know why but well it's something

**Comment by TheUsforcer** [comment]
ok thanks for your time to help me

**Comment by ins0** [comment]
the uploaded logo the one that won't work and the one that work - any difference between the files on upload? same image size? same file? same filename?

**Comment by ins0** [comment]
@TheUsforcer please reupload your logo and test it i updated some libs
