### ISSUE TITLE
Not accepting PlayerID

### ISSUE THREAD

**Issue by BadgerCo** [ins0/armasquads#75]
The system errors out after I input my playerID. 
I tried multiple different IDs and they all work except mine. 
I would post my ID to have you trouble shoot, but I don't want everyone to see it. 
I will gladly PM it.

**Comment by ins0** [comment]
thanks for your report - send me an email "rieger@racecore.de" with your account details (email) or player id and i will try to investigate this issue

**Comment by BadgerCo** [comment]
I feel like an idiot. Turns out it was a duplicate playerID. I'm Closing this and opening a new ticket for another issue I have encountered. 
Thanks,

**Comment by ins0** [comment]
one question to this ticket - did you get a error page after hitting save or nothing happend and the player with the doublicate id only wasn't saved?

**Comment by BadgerCo** [comment]
Error message when hitting save

**Comment by ins0** [comment]
just as reference i reopen this issue and provide a fix for that

**Comment by BadgerCo** [comment]
I think a Duplicate Notification on the error page may help. 
I spent 24 hrs trying to figure this out. 
I felt so dumb :)

**Comment by ins0** [comment]
No you're not dump, the page is dump as you should get a clear and nice error message to let you know what was wrong and how to avoid this :+1:

**Comment by ins0** [comment]
https://github.com/ins0/armasquads/issues/157
