### ISSUE TITLE
Squad Logo not appearing

### ISSUE THREAD

**Issue by BadgerCo** [ins0/armasquads#76]
I have reviewed previous tickets and my issue appears to be unique. 
I do not have "." in my Squad Tag. My image is rendered at 256x256. I uploaded it as a png, and when I download it from the Interface, It has a .paa extension, thus the conversion looks to be working correctly. 
All other elements from the XML work, however, the image is not loading. 
Thoughts?

**Comment by ins0** [comment]
it looks like the converted paa file missing a 2x2 midmap image, i don't know if this is the issue that blocks the logo from showing, will try to test it after i'm back home. can you please keep that squad open and don't modify it?

**Comment by BadgerCo** [comment]
Absolutely, She is all yours. Thanks again for the help :)

**Comment by BadgerCo** [comment]
In the meantime, can I create another Squad XML with a different image file and see if I encounter the same issue?

**Comment by ins0** [comment]
yeah for sure!

**Comment by ins0** [comment]
@BadgerCo please reupload your image and test it please just updated some libs

**Comment by BadgerCo** [comment]
Don't know what you did, but you fixed it. 
Bravo, fine sir, bravo!

**Comment by ins0** [comment]
:+1: nice - thanks for your report! have a nice day!
