### ISSUE TITLE
Go to the server can‘t see the team information and badge

### ISSUE THREAD

**Issue by Sakura-jun** [ins0/armasquads#79]
I discovered recently entered the server don't display team information and badge, I tried to re-establish, but not work.
URL: http://armasquads.com/user/squads/xml/uToYWktnLKdEYhTFkMRRyu1slKRgP6je/squad.xml

**Comment by ins0** [comment]
If this is still an issue, please comment and i will try to help. Logos that are not displayed ingame is in 90% of all tickets a server side problem.
