### ISSUE TITLE
Squad issues

### ISSUE THREAD

**Issue by Spectre011** [ins0/armasquads#83]
well i don't know what i am doing wrong but i added a member yesterday and had him follow the steps i did to get my squad tag and emblem and its not giving him anything it makes it frustrating.. please add a step by step direction page so it can clear up this kind of issue please.. or send me a mail or contact me some how so we can fix this.. also i want to donate but this issue is keeping me from doing so. SO..

**Comment by ins0** [comment]
Currently i'm working on a better error detection when entering squad informations. Arma is verly strict with characters that are not supported. If this issue is still persistent - please comment and i will look into it.
