### ISSUE TITLE
My Squad XML Simply Won't work :'( Im going to cry -.-'

### ISSUE THREAD

**Issue by KoalaFellaz** [ins0/armasquads#84]
I had done Squad XML before, but when i bought a new harddisk, and reinstalled Arma 3 on my PC, and went doing a new Squad XML, and i made it Right with the Right username and ID, but it don't shot anything when i come into arma, even dough i did copy the link into my Profile where the link have to be...

**Comment by ins0** [comment]
if this is still a problem, feel free to comment on this
