### ISSUE TITLE
Error when adding members

### ISSUE THREAD

**Issue by Dyzalonius** [ins0/armasquads#86]
Whenever I try to add a new person to the squad and click on 'save', I get this error screen.
This happened multiple times this week.

![image](https://cloud.githubusercontent.com/assets/13929556/9428248/429bac80-49a6-11e5-9b22-447803266cc0.png)

**Comment by ins0** [comment]
Thanks reporting this error, i will look into it

**Comment by ins0** [comment]
can you please retry you insert and check if the error still occurs?

**Comment by Dyzalonius** [comment]
The error still occurs, no difference.

**Comment by ins0** [comment]
I can't reproduce the error can you please send me the exact information you try to fill in the input fields?

**Comment by Dyzalonius** [comment]
My Squads >> ZEUS Operations >> Members >> Add a new Member >> (see screenshot)
http://i.imgur.com/75Ps4R6.png

**Comment by ins0** [comment]
the user id is allready on the squad xml, currently it is not possible to add the same id twice or more to one squad xml. arma don't recognize multiple user ids on the same squad xml. so instand of this general error you should see a error message saying that adding the same id is not possible.

**Comment by Dyzalonius** [comment]
Oh, I see what happened. I mistaked someone else's SteamID with mine..

**Comment by ins0** [comment]
https://github.com/ins0/armasquads/issues/157
