### ISSUE TITLE
What happened with my squad?

### ISSUE THREAD

**Issue by Ihunter350z** [ins0/armasquads#88]
I was playing Arma just yesterday and my squad worked just fine, but when I changed some lines in the Squad Tile(!!!) and started my game nothing was working, no insigna, no squad, nothing. I tried removing my squad and recreating it anew, restarted my game, re-entered every line manualy and it's still broken. Could I get any suggestions ASAP?

**Comment by ins0** [comment]
Hey Hunter, did you solve your problem?

**Comment by Ihunter350z** [comment]
Yep, turns out my title was too long. Sorry for troubles :D

**Comment by ins0** [comment]
@Ihunter350z did u know how long the title can be, before the xml started to fail?

**Comment by Ihunter350z** [comment]
@ins0 No, I think I could try and test it if you want

**Comment by ins0** [comment]
thanks - this would be nice - if you could test it.
