### ISSUE TITLE
My squad isnt working

### ISSUE THREAD

**Issue by jacobguldner** [ins0/armasquads#89]
it used to work fine, but now, it wont show the logo on any of our things ingame, and i have updated our info to make sure its all acurate, idk what to do, please help. my squad mates are getting upset with me T_T

**Comment by jacobguldner** [comment]
to be a little more clear, all our info for the squad shows in game, ie remarks tag etc, but the logo will not show for anyone other then me, they have the url in the profile, but it still wont show the logo, it used to but now it wont.

**Comment by jacobguldner** [comment]
LOL update, the logo shows on all squad members arms, it shows on my name in the map/players but not the other squad members. it has the big open section on there info in players list where the logo is normally at but its just not apearing in there, it works everywhere else.

this is my squad http://armasquads.com/user/squads/xml/aHNPb0AROMGmSBPOwgzpkQMICOCHgt3D/squad.xml idk if thats the link you need

**Comment by ins0** [comment]
if this is still a problem, feel free to comment on this
