### ISSUE TITLE
Can't add new member to squad

### ISSUE THREAD

**Issue by Tavish101** [ins0/armasquads#94]
Can't add new member to my squad - http://armasquads.com/user/squads/xml/DJGG7GxACqrVh6APcEbbeL1yid17ch16/squad.xml

When I click save it says:
An error occurred during execution; please try again later.

**Comment by ins0** [comment]
is the user id allready present in the squad?

**Comment by Tavish101** [comment]
Yes, My bad. Thanks for an instant reply!

**Comment by ins0** [comment]
You're welcome :)
