### ISSUE TITLE
Neue Member werden nicht angezeigt

### ISSUE THREAD

**Issue by Gotteshand** [ins0/armasquads#95]
Hi Zusammen.

Bei meinem Account funktioniert die Squad.xml aber wenn ich weitere Member hinzufüge scheind dieses nicht zu klappen. Bei Ihnen wird jeder die Gruppe noch das Bild angezeigt.

http://armasquads.de/user/squads/xml/0YFtyQf5xyCynbRgbYy5McgyJVhtihkj/squad.xml

Dieses ist meine Angelegte Gruppe. Vielen Dank für die Hilfe

**Comment by ins0** [comment]
if this is still a problem, feel free to comment on this
