### ISSUE TITLE
Tag and Logo not showing

### ISSUE THREAD

**Issue by MatschbirneLive** [ins0/armasquads#99]
Hello 
Im using the "armasquads" service to host and edit the squad.xml.
I have some issues that i cant get fixed. I removed every space and dots out of the names. 
Remarks and Personal names works just fine but the tag and the Clan Logo is not showing. A other post had a similiar problem and someone said that i should change the logo to this to see if there are enough data in the logo (http://www.w3.org/MarkUp/Test/xhtml-print/20050519/tests/jpeg444.jpg) but it dont work either. Any suggestions that could help ?

**Comment by MatschbirneLive** [comment]
Update: I managed to fix it I wrote my username false *facepalm* if a mod reads this feel free to delete this post

**Comment by ins0** [comment]
thanks @MatschbirneLive for showing others how you resolve your problem :+1:
